spring:
  application:
    name: ApiPrice

  datasource:
    url: jdbc:h2:mem:inditex;
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /api.yaml
